{
 "title": "Crwl Vs Eng",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "query0",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Crawl timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.crawl.std')"
    }
   ]
  },
  {
   "title": "Http Client Timers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.crawl.client.std')"
    }
   ]
  },
  {
   "title": "Html Parser Timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.crawl.parser.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.crawl.parser.upper_90')"
    }
   ]
  },
  {
   "title": "Requests http codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.crawler.crawl.client.code', 'domain=hindiclips.com')"
    }
   ]
  },
  {
   "title": "Queue Take timers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.take.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.take.upper_90')"
    }
   ]
  },
  {
   "title": "Queue put timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.put.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.put.upper_90')"
    }
   ]
  },
  {
   "title": "Queue Enqueue Timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.enqueue.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.enqueue.upper_90')"
    }
   ]
  },
  {
   "title": "Queue EnqueueMany Timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.enqueuemany.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.queue.enqueuemany.upper_90')"
    }
   ]
  },
  {
   "title": "Cache check Timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.cache.check.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.cache.check.upper_90')"
    }
   ]
  },
  {
   "title": "Cache put Timer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "target": "seriesByTag('name=stats.timers.crawler.cache.put.std')"
    },
    {
     "target": "seriesByTag('name=stats.timers.crawler.cache.put.upper_90')"
    }
   ]
  }
 ]
}